// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.mapObjectFactory")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.obstacleChecker")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.spawner")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.zombieFactory")]
[assembly: SuppressMessage("Major Code Smell", "S1117:Local variables should not shadow class fields or properties", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.GroupToOne_MovesTowardsKing")]
[assembly: SuppressMessage("Major Code Smell", "S1117:Local variables should not shadow class fields or properties", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_EnemyMovesAndSetsNewStrategy")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_WhenClosestPlayerFound_CantMove")]
[assembly: SuppressMessage("Major Code Smell", "S1117:Local variables should not shadow class fields or properties", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Test_Move_WhenClosestPlayerIsNull_ShouldNotChangePosition")]
[assembly: SuppressMessage("Major Code Smell", "S4144:Methods should not have identical implementations", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.ObstacleTests.Test_DistanceFromObstacle_Returns_CorrectDistance_FromLeft(System.Int32,System.Int32,System.Double,System.Double,System.Double,System.Double,System.Double)")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Controller_Execute_null")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.mapObjectFactory")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.obstacleChecker")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.spawner")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Class_library_tests.SpawnerTests.zombieFactory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.AdapterTests.Test_JsonString_Convert_ToServerString_Coin")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.AdapterTests.Test_XMLString_Convert_ToServerString_Coin")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Controller_Execute")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Controller_Execute_null")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Controller_Execute_null")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Controller_Execute_Undo")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Execute_Move_Down")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Execute_Move_Left")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Execute_Move_Right")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Execute_Move_Up")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Undo_Move_Down")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Undo_Move_Left")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Undo_Move_Right")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.CommandTests.Test_Undo_Move_Up")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.DecoratorTests.Test_DecorateShield")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.DecoratorTests.Test_DecorateText")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.DecoratorTests.Test_ShowHealthBar")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.CalculateDistance(System.Double,System.Double,System.Double,System.Double)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.GroupToOne_CantMove")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.GroupToOne_MovesTowardsKing")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_EnemyMovesAndSetsNewStrategy")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_WhenClosestPlayerFound_CantMove")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_WhenClosestPlayerFound_CantMove")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Move_WhenClosestPlayerFound_ShouldUpdateEnemyPosition")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Test_Closest_Player_1")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Test_Move_WhenClosestPlayerIsNull_ShouldNotChangePosition")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Test_PatrollingStrategy_ShouldUpdateDirection")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.EnemyTests.Test_PatrollingStrategy_ShouldUpdatePosition")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Create_Coin_With_Factory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Create_Exeption_With_Factory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Create_HealthBoost_With_Factory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Create_Shield_With_Factory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Create_SpeedBoost_With_Factory")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Interact_Player_Coin")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Interact_Player_HealthBoost")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Interact_Player_Shield")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.FactoryTests.Test_Interact_Player_SpeedBoost")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.PrototypeTests.Test_Create_Deep_Copy")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Class_library_tests.PrototypeTests.Test_Create_Shallow_Copy")]
